# Generated by Django 2.0 on 2018-01-03 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='图片')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created', models.DateField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('total_likes', models.PositiveIntegerField(db_index=True, default=0, verbose_name='点赞数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_created', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('users_like', models.ManyToManyField(blank=True, related_name='images_liked', to=settings.AUTH_USER_MODEL, verbose_name='喜爱这张照片的用户')),
            ],
            options={
                'verbose_name': '图片',
                'ordering': ('-created',),
                'verbose_name_plural': '图片',
            },
        ),
    ]
