# Generated by Django 2.0 on 2017-12-31 11:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExmSentence',
            fields=[
                ('ES_id', models.AutoField(primary_key=True, serialize=False)),
                ('ES_sen', models.TextField()),
                ('ES_definition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('Nid', models.AutoField(max_length=4, primary_key=True, serialize=False)),
                ('Ndate', models.DateTimeField(default=datetime.datetime(2017, 12, 31, 11, 21, 48, 107022))),
                ('Ncontent', models.TextField()),
                ('Ntitle_cn', models.CharField(max_length=60)),
                ('Ntitle_en', models.CharField(max_length=60)),
                ('Nstatus', models.CharField(choices=[('pub', 'publish'), ('ver', 'verify'), ('f', 'fail')], max_length=12)),
                ('Ncomment_status', models.CharField(choices=[('o', 'open'), ('c', 'close')], max_length=12)),
                ('Npost_modified', models.DateTimeField(default=datetime.datetime(2017, 12, 31, 11, 21, 48, 107246))),
                ('Npost_parent', models.IntegerField()),
                ('Nlength', models.IntegerField(max_length=3)),
                ('Ngrade_info', models.CharField(max_length=14)),
                ('Nhas_audio', models.BooleanField(default=True)),
                ('Nhas_video', models.BooleanField(default=False)),
                ('Nsummary', models.TextField()),
                ('Nnum_reviews', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('Uid', models.AutoField(primary_key=True, serialize=False)),
                ('Uname', models.CharField(max_length=30)),
                ('Uaccount', models.CharField(max_length=30)),
                ('Upass', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserBaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UBage', models.IntegerField()),
                ('UBemail', models.CharField(max_length=50)),
                ('UBfriend', models.IntegerField()),
                ('UBsignature', models.CharField(max_length=100)),
                ('UBsex', models.BooleanField()),
                ('UBphone_number', models.IntegerField()),
                ('UBprofile_photo_url', models.URLField()),
                ('UBid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserAccount')),
            ],
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('UBcomment_id', models.AutoField(max_length=4, primary_key=True, serialize=False)),
                ('UBcomment_date', models.DateTimeField(default=datetime.datetime(2017, 12, 31, 11, 21, 48, 105324))),
                ('UBcomment', models.CharField(max_length=200)),
                ('UBcomment_to', models.IntegerField()),
                ('UBcomment_IP', models.CharField(max_length=50)),
                ('UBcomment_approved', models.BooleanField(default='TRUE')),
                ('UBcomment_parent', models.IntegerField()),
                ('UBComment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserAccount')),
            ],
        ),
        migrations.CreateModel(
            name='UserNewsMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finished', models.BooleanField(default=False)),
                ('is_liked', models.BooleanField(default=False)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('UNM_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.News')),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Voc_id', models.IntegerField()),
                ('cn_definition', models.CharField(max_length=80)),
                ('en_definition', models.CharField(max_length=80)),
                ('content', models.CharField(max_length=30)),
                ('content_type', models.CharField(choices=[('voc', 'vocabulary'), ('ph', 'phrase')], max_length=12)),
                ('uk_audio', models.URLField()),
                ('us_audio', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='Nauthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserBaseInfo'),
        ),
        migrations.AddField(
            model_name='exmsentence',
            name='ES_voc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Vocabulary'),
        ),
    ]
