# Generated by Django 2.0 on 2017-12-31 18:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExmSentence',
            fields=[
                ('ES_id', models.AutoField(primary_key=True, serialize=False)),
                ('ES_sen', models.TextField()),
                ('ES_definition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('Nid', models.AutoField(max_length=4, primary_key=True, serialize=False)),
                ('Ndate', models.DateTimeField(auto_now_add=True)),
                ('Ncontent', models.TextField()),
                ('Ntitle_cn', models.CharField(max_length=60)),
                ('Ntitle_en', models.CharField(max_length=60)),
                ('Nstatus', models.CharField(choices=[('pub', 'publish'), ('ver', 'verify'), ('f', 'fail')], max_length=12)),
                ('Ncomment_status', models.CharField(choices=[('o', 'open'), ('c', 'close')], max_length=12)),
                ('Npost_modified', models.DateTimeField(auto_now=True)),
                ('Npost_parent', models.IntegerField()),
                ('Nlength', models.IntegerField(max_length=3)),
                ('Ngrade_info', models.CharField(max_length=14)),
                ('Nhas_audio', models.BooleanField(default='True')),
                ('Nhas_video', models.BooleanField(default=False)),
                ('Nsummary', models.TextField()),
                ('Nnum_reviews', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uname', models.CharField(max_length=30)),
                ('Uaccount', models.CharField(max_length=30)),
                ('Upass', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserBaseInfo',
            fields=[
                ('UBage', models.IntegerField()),
                ('UBemail', models.CharField(max_length=50)),
                ('UBfriend', models.IntegerField()),
                ('UBsignature', models.CharField(max_length=100)),
                ('UBsex', models.BooleanField()),
                ('UBphone_number', models.IntegerField()),
                ('UBprofile_photo_url', models.URLField()),
                ('UBid', models.AutoField(primary_key=True, serialize=False)),
                ('UBfollowing_num', models.IntegerField()),
                ('UBfollower_num', models.IntegerField()),
                ('UBreading_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('UBcomment_id', models.AutoField(max_length=4, primary_key=True, serialize=False)),
                ('UBcomment_date', models.DateTimeField(default=datetime.datetime(2017, 12, 31, 18, 5, 41, 417104))),
                ('UBcomment', models.CharField(max_length=200)),
                ('UBcomment_to', models.IntegerField()),
                ('UBcomment_IP', models.CharField(max_length=50)),
                ('UBcomment_approved', models.BooleanField(default='TRUE')),
                ('UBcomment_parent', models.IntegerField()),
                ('UBreading_play_num', models.IntegerField()),
                ('UBComment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserBaseInfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserFollower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UF_friend_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_id', to='user.UserBaseInfo')),
                ('UF_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserBaseInfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserJournal',
            fields=[
                ('UJ_id', models.AutoField(primary_key=True, serialize=False)),
                ('UJ_title', models.CharField(max_length=50)),
                ('UJ_content', models.TextField()),
                ('UJ_create_date', models.DateField(auto_now_add=True)),
                ('UJ_update_date', models.DateField(auto_now=True)),
                ('UJ_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserBaseInfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserNewsMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finished', models.BooleanField(default=False)),
                ('is_liked', models.BooleanField(default=False)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('UNM_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.News')),
            ],
        ),
        migrations.CreateModel(
            name='UserResource',
            fields=[
                ('R_id', models.AutoField(primary_key=True, serialize=False)),
                ('R_name', models.CharField(max_length=50)),
                ('R_price', models.FloatField(default=0.0)),
                ('R_url', models.URLField()),
                ('R_has', models.BooleanField(default='True')),
                ('R_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserBaseInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Voc_id', models.IntegerField()),
                ('cn_definition', models.CharField(max_length=80)),
                ('en_definition', models.CharField(max_length=80)),
                ('content', models.CharField(max_length=30)),
                ('content_type', models.CharField(choices=[('voc', 'vocabulary'), ('ph', 'phrase')], max_length=12)),
                ('uk_audio', models.URLField()),
                ('us_audio', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='WordSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WS_voc_book', models.CharField(max_length=20)),
                ('WS_pronunciation', models.IntegerField(choices=[(0, '美式'), (1, '英式')])),
                ('WS_translate_en', models.BooleanField(default='True')),
                ('WS_translate_cn', models.BooleanField(default='True')),
                ('WS_voc_auto_pron', models.BooleanField(default='True')),
                ('WS_sentence_auto_pron', models.BooleanField(default='True')),
                ('WS_disp_note', models.BooleanField(default='True')),
                ('WS_stu_degree', models.IntegerField(choices=[(0, '再认'), (1, '拼写')])),
                ('WS_stu_times', models.IntegerField(default=5)),
                ('WS_stu_volume', models.IntegerField(default=100)),
                ('WS_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserAccount')),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='Uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserBaseInfo'),
        ),
        migrations.AddField(
            model_name='news',
            name='Nauthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserBaseInfo'),
        ),
        migrations.AddField(
            model_name='exmsentence',
            name='ES_voc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Vocabulary'),
        ),
    ]
